<h1>Atividade 02 - melhorar o desempenho de RP em conjunto de dados existentes</h1>
<p>A atividade 02 visa trabalhar com um conjunto de dados pré-construído, onde as opções que o desenvolvedor tem, são de aplicar as técnicas de pré-processamento abaixo relacionadas:</p>
<ul><li>Seleção</li>
<li>Limpeza</li>
<li>Codificação</li>
<li>Enriquecimento</li>
<li>Normalização</li>
<li>Construção de Atributos</li>
<li>Correção de Prevalência</li>
<li>Partição do Conjunto de Dados</li>
</ul>
<p>Busque uma base de dados na UCI Machine Learning que seja indicada para problemas de classificação. (<a target="_blank" href="https://archive.ics.uci.edu/datasets">https://archive.ics.uci.edu/datasets</a>)</p>
<p>Para esse exemplo, vou usar a base de câncer de mama (https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic)</p>


Opção 01 - carregue o arquivo de dados da pasta local para o colab.


In [3]:
import numpy as np
import pandas as pd
#
# base de dados disponível na UCI Machine Learning - https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic
cancer_colunas = ['id','Diagnosis',
                  'radius_mean','texture_mean','perimeter_mean', 'area_mean',
                  'smoothness_mean','compactness_mean','concavity_mean',
                  'concave_mean','symmetry_mean','fractal_mean',

                  'radius_se','texture_se','perimeter_se', 'area_se','smoothness_se',
                  'compactness_se','concavity_se','concave_se','symmetry_se','fractal_se'

                  'radius_worst','texture_worst','perimeter_worst', 'area_worst',
                  'smoothness_worst','compactness_worst','concavity_worst',
                  'concave_worst','symmetry_worst','fractal_worst']
cancer = pd.read_csv('/content/wdbc.data',header=None,
                     names=cancer_colunas, lineterminator='\n', na_values='?')

# visualizar parte dos dados
print( cancer.head() )

#
# caso queira usar do google-drivre
#from google.colab import drive
#drive.mount('/content/drive')
#drive.mount(“/content/drive”, force_remount=True)

         id  Diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
842302    M      17.99        10.38        122.80          1001.0    0.11840   
842517    M      20.57        17.77        132.90          1326.0    0.08474   
84300903  M      19.69        21.25        130.00          1203.0    0.10960   
84348301  M      11.42        20.38         77.58           386.1    0.14250   
84358402  M      20.29        14.34        135.10          1297.0    0.10030   

          smoothness_mean  compactness_mean  concavity_mean  concave_mean  \
842302            0.27760            0.3001         0.14710        0.2419   
842517            0.07864            0.0869         0.07017        0.1812   
84300903          0.15990            0.1974         0.12790        0.2069   
84348301          0.28390            0.2414         0.10520        0.2597   
84358402          0.13280            0.1980         0.10430        0.1809   

          ...  fractal_seradius_worst  texture_worst  pe

Para baixar direto da web e tratar arquivos compactados, sem o uso de arquivos locais.


In [32]:
import requests, zipfile, io
from io import BytesIO
import numpy as np
import pandas as pd

r = requests.get('https://archive.ics.uci.edu/static/public/17/breast+cancer+wisconsin+diagnostic.zip')
z = zipfile.ZipFile(io.BytesIO(r.content))
z.namelist()
dadosfp = z.open('wdbc.data')
dados = dadosfp.read()
cancer2 = pd.read_csv(io.BytesIO(dados),header=None,
                     names=cancer_colunas, lineterminator='\n', na_values='?')
print( cancer.head() )

cancer.describe()

         id  Diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
842302    M      17.99        10.38        122.80          1001.0    0.11840   
842517    M      20.57        17.77        132.90          1326.0    0.08474   
84300903  M      19.69        21.25        130.00          1203.0    0.10960   
84348301  M      11.42        20.38         77.58           386.1    0.14250   
84358402  M      20.29        14.34        135.10          1297.0    0.10030   

          smoothness_mean  compactness_mean  concavity_mean  concave_mean  \
842302            0.27760            0.3001         0.14710        0.2419   
842517            0.07864            0.0869         0.07017        0.1812   
84300903          0.15990            0.1974         0.12790        0.2069   
84348301          0.28390            0.2414         0.10520        0.2597   
84358402          0.13280            0.1980         0.10430        0.1809   

          ...  fractal_seradius_worst  texture_worst  pe

Diagnosis  radius_mean  texture_mean  perimeter_mean   area_mean  \
count  569.000000   569.000000    569.000000      569.000000  569.000000   
mean    14.127292    19.289649     91.969033      654.889104    0.096360   
std      3.524049     4.301036     24.298981      351.914129    0.014064   
min      6.981000     9.710000     43.790000      143.500000    0.052630   
25%     11.700000    16.170000     75.170000      420.300000    0.086370   
50%     13.370000    18.840000     86.240000      551.100000    0.095870   
75%     15.780000    21.800000    104.100000      782.700000    0.105300   
max     28.110000    39.280000    188.500000     2501.000000    0.163400   

       smoothness_mean  compactness_mean  concavity_mean  concave_mean  \
count       569.000000        569.000000      569.000000    569.000000   
mean          0.104341          0.088799        0.048919      0.181162   
std           0.052813          0.079720        0.038803      0.027414   
min           0.019380          0.000000        0.000000      0.106000   
25%           0.064920          0.029560        0.020310      0.161900   
50%           0.092630          0.061540        0.033500      0.179200   
75%           0.130400          0.130700        0.074000      0.195700   
max           0.345400          0.426800        0.201200      0.304000   

       symmetry_mean  ...  fractal_seradius_worst  texture_worst  \
count     569.000000  ...              569.000000     569.000000   
mean        0.062798  ...               16.269190      25.677223   
std         0.007060  ...                4.833242       6.146258   
min         0.049960  ...                7.930000      12.020000   
25%         0.057700  ...               13.010000      21.080000   
50%         0.061540  ...               14.970000      25.410000   
75%         0.066120  ...               18.790000      29.720000   
max         0.097440  ...               36.040000      49.540000   

       perimeter_worst   area_worst  smoothness_worst  compactness_worst  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       concavity_worst  concave_worst  symmetry_worst  fractal_worst  
count       569.000000     569.000000      569.000000     569.000000  
mean          0.272188       0.114606        0.290076       0.083946  
std           0.208624       0.065732        0.061867       0.018061  
min           0.000000       0.000000        0.156500       0.055040  
25%           0.114500       0.064930        0.250400       0.071460  
50%           0.226700       0.099930        0.282200       0.080040  
75%           0.382900       0.161400        0.317900       0.092080  
max           1.252000       0.291000        0.663800       0.207500  

[8 rows x 30 columns]

<h2>Hora de realizar os tratamentos<h2>
<p>no exemplo, iremos normalizar as colunas, remover a coluna de identificação e separar a classe dos atributos.</p>

In [89]:
X = cancer.iloc[:,2:]
cols = cancer_colunas[2:]
print(X.head())
Y = cancer['id']
Y_orig = cancer['id']
print(Y.unique())

          radius_mean  texture_mean  perimeter_mean  area_mean  \
842302          10.38        122.80          1001.0    0.11840   
842517          17.77        132.90          1326.0    0.08474   
84300903        21.25        130.00          1203.0    0.10960   
84348301        20.38         77.58           386.1    0.14250   
84358402        14.34        135.10          1297.0    0.10030   

          smoothness_mean  compactness_mean  concavity_mean  concave_mean  \
842302            0.27760            0.3001         0.14710        0.2419   
842517            0.07864            0.0869         0.07017        0.1812   
84300903          0.15990            0.1974         0.12790        0.2069   
84348301          0.28390            0.2414         0.10520        0.2597   
84358402          0.13280            0.1980         0.10430        0.1809   

          symmetry_mean  fractal_mean  ...  fractal_seradius_worst  \
842302          0.07871        1.0950  ...                   25.38   


Na próxima seção que deverão ser realizada as tentativas de tratamento de dados, visando a melhoria no desempenho do classificador (SVM).

In [90]:
from sklearn.preprocessing import scale
from sklearn.preprocessing import minmax_scale
import pandas as pd

X_orig =  X.copy()
print(X_orig.head())

print(Y_orig.unique() )

# normalização min-max
X = pd.DataFrame( minmax_scale(X) )

print(X_orig.head())
print(X.head())

# A normalização pode ser manual, usando o pandas... ex:
#X['radius_mean'] = (X_orig['radius_mean']-X_orig['radius_mean'].mean()) / X_orig['radius_mean'].std()
# normalização min-max
#X['texture_mean'] = (X_orig['texture_mean']-X_orig['texture_mean'].min()) / (X_orig['texture_mean'].max()-X_orig['texture_mean'].min())

          radius_mean  texture_mean  perimeter_mean  area_mean  \
842302          10.38        122.80          1001.0    0.11840   
842517          17.77        132.90          1326.0    0.08474   
84300903        21.25        130.00          1203.0    0.10960   
84348301        20.38         77.58           386.1    0.14250   
84358402        14.34        135.10          1297.0    0.10030   

          smoothness_mean  compactness_mean  concavity_mean  concave_mean  \
842302            0.27760            0.3001         0.14710        0.2419   
842517            0.07864            0.0869         0.07017        0.1812   
84300903          0.15990            0.1974         0.12790        0.2069   
84348301          0.28390            0.2414         0.10520        0.2597   
84358402          0.13280            0.1980         0.10430        0.1809   

          symmetry_mean  fractal_mean  ...  fractal_seradius_worst  \
842302          0.07871        1.0950  ...                   25.38   


A próxima seção trata da construção do modelo, dos testes e das métricas da matriz de confusão.

In [91]:
from sklearn.model_selection import train_test_split
import numpy as np

# com os dados originais
X_oring_train, X_orig_test, y_orig_train, y_orig_test = train_test_split(X_orig,
                      Y_orig, test_size=0.25, stratify=Y_orig,random_state=10)

# com os dados tratados
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25,
                                                    stratify=Y,random_state=10)

Treina o modelo com base nos dados originais (SVM).

In [92]:

from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido

modelo_orig = treinador.fit(X_oring_train, y_orig_train)

# predição com os mesmos dados usados para treinar
y_orig_pred = modelo_orig.predict(X_oring_train)
cm_orig_train = confusion_matrix(y_orig_train, y_orig_pred)
print('Matriz de confusão - com os dados ORIGINAIS usados no TREINAMENTO')
print(cm_orig_train)
print(classification_report(y_orig_train, y_orig_pred))

# predição com os mesmos dados usados para testar
print('Matriz de confusão - com os dados ORIGINAIS usados para TESTES')
y2_orig_pred = modelo_orig.predict(X_orig_test)
cm_orig_test = confusion_matrix(y_orig_test, y2_orig_pred)
print(cm_orig_test)
print(classification_report(y_orig_test, y2_orig_pred))


Matriz de confusão - com os dados ORIGINAIS usados no TREINAMENTO
[[265   2]
 [ 34 125]]
              precision    recall  f1-score   support

           B       0.89      0.99      0.94       267
           M       0.98      0.79      0.87       159

    accuracy                           0.92       426
   macro avg       0.94      0.89      0.91       426
weighted avg       0.92      0.92      0.91       426

Matriz de confusão - com os dados ORIGINAIS usados para TESTES
[[87  3]
 [ 9 44]]
              precision    recall  f1-score   support

           B       0.91      0.97      0.94        90
           M       0.94      0.83      0.88        53

    accuracy                           0.92       143
   macro avg       0.92      0.90      0.91       143
weighted avg       0.92      0.92      0.91       143



Como os dados ficam após os processos de tratamento dos dados?

In [93]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido

modelo = treinador.fit(X_train, y_train)

# predição com os mesmos dados usados para treinar
y_pred = modelo.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred)
print('Matriz de confusão - com os dados TRATADOS usados no TREINAMENTO')
print(cm_train)
print(classification_report(y_train, y_pred))

# predição com os mesmos dados usados para testar
print('Matriz de confusão - com os dados ORIGINAIS usados para TESTES')
y2_pred = modelo.predict(X_test)
cm_test = confusion_matrix(y_test, y2_pred)
print(cm_test)
print(classification_report(y_test, y2_pred))


Matriz de confusão - com os dados TRATADOS usados no TREINAMENTO
[[267   0]
 [  8 151]]
              precision    recall  f1-score   support

           B       0.97      1.00      0.99       267
           M       1.00      0.95      0.97       159

    accuracy                           0.98       426
   macro avg       0.99      0.97      0.98       426
weighted avg       0.98      0.98      0.98       426

Matriz de confusão - com os dados ORIGINAIS usados para TESTES
[[89  1]
 [ 1 52]]
              precision    recall  f1-score   support

           B       0.99      0.99      0.99        90
           M       0.98      0.98      0.98        53

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143

