<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [481]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [482]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['¿Qué hora es?', 'espanhol'], ['Você já visitou o Rio de Janeiro?', 'português'], ['I need to buy some groceries.', 'inglês'], ['¿Cuál es tu comida favorita?', 'espanhol'], ['¿Cómo estuvo tu fin de semana?', 'espanhol'], ['O restaurante tem uma vista incrível.', 'português'], ['Vamos a dar un paseo.', 'espanhol'], ['Estoy emocionado por el concierto.', 'espanhol'], ['¿Dónde puedo encontrar un taxi?', 'espanhol'], ['Where can I find a taxi?', 'inglês'], ['What time is it?', 'inglês'], ["I'm planning a vacation.", 'inglês'], ['Vamos sair para jantar no sábado.', 'português'], ['Preciso comprar leite e pão.', 'português'], ['Could you pass me the salt, please?', 'inglês'], ['Meu time de futebol favorito ganhou o jogo.', 'português'], ['¡Que tengas un buen día!', 'espanhol'], ['Do you have any recommendations for restaurants?', 'inglês'], ['Where is the nearest restaurant?', 'inglês'], ['A comida estava deliciosa!', 'português'], ['¿Puedes ayudarme con esto?', 'espanhol'], ['El clima est

O DataFrame do pandas facilita a visualização.

In [483]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0                                       ¿Qué hora es?   espanhol
1                   Você já visitou o Rio de Janeiro?  português
2                       I need to buy some groceries.     inglês
3                        ¿Cuál es tu comida favorita?   espanhol
4                      ¿Cómo estuvo tu fin de semana?   espanhol
..                                                ...        ...
87                           Ella canta hermosamente.   espanhol
88             Estou ansioso para as férias de verão.  português
89                  Estou indo para o trabalho agora.  português
90                                Hello, how are you?     inglês
91  Estou cansado depois de um longo dia de trabalho.  português

[92 rows x 2 columns]

In [484]:
# A criação de ngrams com o modelo TfidfVectorizer foi uma tentativa, porém não melhorou a acurácio do treinamento, por isso não foi utilizada, mas deixamos aqui como documentação que foi explorada.
import numpy as np
import re
from sklearn.feature_extraction.text import TfidfVectorizer

pre_padroes_np = np.array(pre_padroes)
pattern_regex = re.compile('[^\w+]', re.UNICODE)
corpus = [re.sub(pattern_regex, ' ', str(item)) for item in pre_padroes_np[:, 0]]
print(corpus)

ngram_model = TfidfVectorizer(analyzer='char', ngram_range=(3, 5))
ngram_model.fit_transform(corpus)

[' Qué hora es ', 'Você já visitou o Rio de Janeiro ', 'I need to buy some groceries ', ' Cuál es tu comida favorita ', ' Cómo estuvo tu fin de semana ', 'O restaurante tem uma vista incrível ', 'Vamos a dar un paseo ', 'Estoy emocionado por el concierto ', ' Dónde puedo encontrar un taxi ', 'Where can I find a taxi ', 'What time is it ', 'I m planning a vacation ', 'Vamos sair para jantar no sábado ', 'Preciso comprar leite e pão ', 'Could you pass me the salt  please ', 'Meu time de futebol favorito ganhou o jogo ', ' Que tengas un buen día ', 'Do you have any recommendations for restaurants ', 'Where is the nearest restaurant ', 'A comida estava deliciosa ', ' Puedes ayudarme con esto ', 'El clima está agradable hoy ', 'Estoy planeando unas vacaciones ', 'A festa começa às 20h ', 'Vou viajar para o exterior nas férias ', 'How was your weekend ', 'Este es mi libro favorito ', 'Gosto de fazer caminhadas na natureza ', 'Me encanta leer libros ', 'Let s go for a walk ', 'She sings beaut

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7296 stored elements and shape (92, 4748)>

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [485]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re

from scipy.sparse import hstack

def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)


def caracteresEspeciais(frase):
    return 1 if any(ord(char) > 127 for char in frase) else 0

def possuiDoisSimbolosSucessivos(frase):
    frase = frase.lower();
    for i in range(len(frase) - 1):
        if frase[i] == frase[i+1]:
            return 1;
    return 0;

def proporcaoDeSufixos(frase):
    sufixos_por_idioma = {
        0: ["mente", "dade", "eiro", "ista", "oso", "ável", "ível", "ência", "idade", "ização", "amento", "imento", "ar", "ado", "ada"],   # Português
        1: ["ción", "ciones", "dad", "tad", "ero", "encia", "iendo", "amiento", "imiento", "mente", "oy", "ando", "nte", "nta"], # Espanhol
        2: ["ing", "ed", "ly", "ness", "ment", "able", "ible", "tion", "sion", "ous"]   # Inglês		
    }
    palavras = frase.lower().split()
    contador = [0.0,0.0,0.0]
    for palavra in palavras:
        for posicao, sufixos in sufixos_por_idioma.items():
            for sufixo in sufixos:
                if palavra.endswith(sufixo):
                    contador[posicao] += 1            
    total_palavras = len(palavras)
    for i in range(len(contador)):
        if (contador[i] != 0):
            contador[i] /= total_palavras            
    return contador

# retorna um array com a contagem de cada lingua
# posição 0 - pt, posição 1 - es, posição 2 - en
# logo a função será quebrada em 3 caracteristicas
def contagemPalavrasFrequentes(frase):
    palavras_pt = ["que", "não", "porém", "então", "porque", "lá", "saudade", "para", "de", "no", "ao", "estou", "você", "um", "uma", "em", "e", "o", "a", "os", "as", "ele", "ela", "eles", "elas"]
    palavras_es = ["no", "pero", "entonces", "el", "la", "es", "un", "estoy", "cómo", "tu", "gusta", "cuál", "ella", "de", "en", "que", "y", "los", "las", "él", "ella", "ellos", "ellas", "aquí", "ustedes"]
    palavras_en = ["the", "and", "but", "because", "there", "add", "sadness", "you", "i m", "to", "this", "have", "of", "in", "that", "a", "an", "he", "they"]
        
    frase = frase.lower();
    palavras = frase.lower().split()
    contador = [0,0,0]    
    for p in palavras:
        if p in palavras_pt:
            contador[0] += 1
        if p in palavras_es:
            contador[1] += 1
        if p in palavras_en:
            contador[2] += 1
    return contador

def proporcaoAcentosPtEs(frase):
    acentos_pt_es = ['â', 'ê', 'ô', 'ã', 'õ', 'á', 'é', 'í', 'ó', 'ú', 'à']
    frase = frase.lower();
    total_acentos = sum(frase.count(c) for c in acentos_pt_es)
    return total_acentos / len(frase)

def criaNGrans(frase):
    x = ngram_model.transform([frase])
    return x.toarray()

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  #print(texto)
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  #print(texto)  
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=caracteresEspeciais(texto)
  caracteristica3=possuiDoisSimbolosSucessivos(texto)
  caracteristica4=proporcaoAcentosPtEs(texto)    
  caracteristica6, caracteristica7, caracteristica8 = contagemPalavrasFrequentes(texto)
  caracteristica9, caracteristica10, caracteristica11 = proporcaoDeSufixos(texto)
  # acrescente as suas funcoes no vetor padrao
  vetor_tfidf=criaNGrans(texto)  
  padrao = [caracteristica1, caracteristica2, caracteristica3, caracteristica4, caracteristica6, caracteristica7, caracteristica8, caracteristica9, caracteristica10, caracteristica11, frase[1]]
  padrao_array = np.array(padrao)
  #pdrao_combinado = hstack([vetor_tfidf, padrao_array])  # use sparse hstack
  #padrao_combinado = np.append(vetor_tfidf[0].tolist(), padrao_array)  # use sparse hstack
  #return np.append(vetor_tfidf[0].tolist(), frase[1]).tolist()
  #return padrao_combinado.tolist()
  return padrao


def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

[[3.0, 1, 0, 0.07692307692307693, 0, 1, 0, 0.0, 0.0, 0.0, 'espanhol'], [3.7142857142857144, 1, 0, 0.06060606060606061, 3, 1, 0, 0.14285714285714285, 0.0, 0.0, 'português'], [3.8333333333333335, 0, 1, 0.0, 0, 0, 1, 0.0, 0.0, 0.16666666666666666, 'inglês'], [4.4, 1, 0, 0.03571428571428571, 0, 3, 0, 0.0, 0.0, 0.0, 'espanhol'], [3.8333333333333335, 1, 0, 0.03333333333333333, 1, 3, 0, 0.0, 0.0, 0.0, 'espanhol'], [5.166666666666667, 1, 0, 0.02702702702702703, 2, 0, 0, 0.3333333333333333, 0.16666666666666666, 0.0, 'português'], [3.2, 0, 0, 0.0, 1, 1, 1, 0.2, 0.0, 0.0, 'espanhol'], [5.8, 0, 0, 0.0, 0, 2, 0, 0.2, 0.2, 0.0, 'espanhol'], [5.0, 1, 0, 0.03225806451612903, 0, 1, 0, 0.2, 0.0, 0.0, 'espanhol'], [3.0, 0, 0, 0.0, 1, 0, 1, 0.0, 0.0, 0.0, 'inglês'], [3.0, 0, 0, 0.0, 0, 0, 0, 0.0, 0.0, 0.0, 'inglês'], [3.8, 0, 1, 0.0, 1, 0, 1, 0.0, 0.0, 0.4, 'inglês'], [4.5, 1, 0, 0.030303030303030304, 2, 1, 0, 0.3333333333333333, 0.0, 0.0, 'português'], [4.6, 1, 0, 0.03571428571428571, 1, 0, 0, 0.2, 0.0, 

0   1   2         3   4   5   6         7    8         9          10
0   3.000000   1   0  0.076923   0   1   0  0.000000  0.0  0.000000   espanhol
1   3.714286   1   0  0.060606   3   1   0  0.142857  0.0  0.000000  português
2   3.833333   0   1  0.000000   0   0   1  0.000000  0.0  0.166667     inglês
3   4.400000   1   0  0.035714   0   3   0  0.000000  0.0  0.000000   espanhol
4   3.833333   1   0  0.033333   1   3   0  0.000000  0.0  0.000000   espanhol
..       ...  ..  ..       ...  ..  ..  ..       ...  ...       ...        ...
87  7.000000   0   1  0.000000   0   1   0  0.333333  1.0  0.000000   espanhol
88  4.428571   1   0  0.052632   4   1   0  0.142857  0.0  0.000000  português
89  4.500000   0   0  0.000000   3   0   0  0.000000  0.0  0.000000  português
90  3.500000   0   1  0.000000   0   0   1  0.000000  0.0  0.000000     inglês
91  4.444444   0   0  0.000000   4   2   0  0.111111  0.0  0.000000  português

[92 rows x 11 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [486]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes, random_state=42)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [487]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC(random_state=42)  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 89.86%
[[17  3  2]
 [ 0 23  0]
 [ 2  0 22]]
              precision    recall  f1-score   support

    espanhol       0.89      0.77      0.83        22
      inglês       0.88      1.00      0.94        23
   português       0.92      0.92      0.92        24

    accuracy                           0.90        69
   macro avg       0.90      0.90      0.89        69
weighted avg       0.90      0.90      0.90        69

métricas mais confiáveis
[[7 0 1]
 [1 6 0]
 [0 1 7]]
              precision    recall  f1-score   support

    espanhol       0.88      0.88      0.88         8
      inglês       0.86      0.86      0.86         7
   português       0.88      0.88      0.88         8

    accuracy                           0.87        23
   macro avg       0.87      0.87      0.87        23
weighted avg       0.87      0.87      0.87        23

